import { useEffect, useMemo, useState } from "react";

type ProjectKey = "demand" | "route" | "agent";
type Project = { key: ProjectKey; index: string; title: string; thesis: string; question: string; result: string; resultNote: string; proof: string[]; stack: string; image: string; detailImage: string; lab: string; source: string; caveat: string; };

const projects: Project[] = [
  { key:"demand", index:"01", title:"DEMAND / ORDER", thesis:"From a forecast score to a replenishment decision.", question:"What should a planner review, and how much service buffer is defensible?", result:"1,528", resultNote:"fewer simulated lost units", proof:["900 item-store series","4.5% lower WAPE vs selected baseline","96.7% simulated fulfilled demand"], stack:"Python / scikit-learn / forecasting / policy simulation / React", image:"./images/projects/demand-overview.png", detailImage:"./images/projects/demand-detail.png", lab:"./labs/demand/index.html", source:"./evidence/demand-order.md", caveat:"M5 28-day holdout; policy outcomes are simulation, not realized savings." },
  { key:"route", index:"02", title:"ROUTE / CONTROL", thesis:"A route policy a dispatcher can interrogate.", question:"Which sequence balances drive time, timed packages and route coherence?", result:"85.2 min", resultNote:"less simulated drive time", proof:["6,112 historical routes","100% timed-package adherence","332 to 0 zone re-entries"], stack:"Python / sequence learning / constrained local search / React", image:"./images/projects/route-control.png", detailImage:"./images/projects/route-detail.png", lab:"./labs/route/index.html", source:"./evidence/route-control.md", caveat:"Separate 13-route public cohort; retrospective simulation, not a production claim." },
  { key:"agent", index:"03", title:"AGENT / PROOF", thesis:"One pass is not reliability.", question:"Which agent is repeatable enough to release, and what fails first?", result:"14.9 pts", resultNote:"repeatability loss exposed", proof:["3,336 official trajectories","4 trials per task","99.0% missing-action diagnostic share"], stack:"Python / agent evaluation / statistics / failure diagnostics / React", image:"./images/projects/agent-proof.png", detailImage:"./images/projects/agent-detail.png", lab:"./labs/agent/index.html", source:"./evidence/agent-proof.md", caveat:"Pinned historical tau2-bench cohort; no live calls or current-production claim." }
];

const timeline = [
  { period:"MAR 2026 - NOW", company:"MAGNA INTERNATIONAL", place:"KENITRA, MOROCCO", role:"Supplier Quality Engineer / Electronics & Metal", statement:"Turning launch activity, supplier performance and open issues into a traceable decision layer.", details:["Built a full SQE BI system spanning nomination, launch, Safe Launch and SOP, with critical-part views and meaningful issue insights.","Designed a smart notification pipeline to keep owners, milestones and overdue actions visible across the activity portfolio.","Coordinate supplier quality across Europe, Asia and Morocco while protecting confidential supplier and customer information."] },
  { period:"FEB - AUG 2025", company:"STELLANTIS R&D", place:"CASABLANCA, MOROCCO", role:"Engineering Intern / Data Analytics, Process Optimization & AI", statement:"Reduced a configuration-anomaly workflow from two days to two minutes.", details:["Mapped the operational workflow, structured its status logic and built a Python application backed by a Databricks data model for detection, prioritization and treatment traceability."] },
  { period:"JUL - SEP 2024", company:"SANY / FORGE DE BAZAS", place:"CASABLANCA, MOROCCO", role:"Engineering Intern / Process Digitalization & Maintenance", statement:"Made maintenance knowledge easier to retrieve and use on the shop floor.", details:["Built a Unity/NLP assistant that structured access to maintenance and spare-parts information while preserving a traceable knowledge flow."] },
  { period:"AUG - SEP 2023", company:"3D SMART FACTORY", place:"MOHAMMEDIA, MOROCCO", role:"Data Analyst Intern", statement:"Converted production records into visual operating signals.", details:["Built Power BI and Excel reporting around OEE, FPY, scrap and downtime to expose bottlenecks for Lean review."] }
];

function Header(){ const[open,setOpen]=useState(false); const nav=[["Work","#work"],["Method","#method"],["Experience","#experience"],["Profile","#profile"],["Contact","#contact"]]; return <header className="site-header"><a className="wordmark" href="#top"><span>RM</span> / DECISION ENGINEER</a><nav className={open?"open":""} aria-label="Primary">{nav.map(([label,href])=><a key={href} href={href} onClick={()=>setOpen(false)}>{label}</a>)}</nav><a className="resume-link" href="./documents/Rida_Melkaoui_Data_AI_Resume.pdf" download>RESUME v</a><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(!open)}><i></i><i></i><i></i></button></header> }

function Hero(){ return <section className="hero" id="top"><div className="hero-copy"><div className="kicker">INDUSTRIAL ENGINEER / DATA + AI / BI</div><h1>I BUILD<br/><em>DECISION</em><br/>SYSTEMS.</h1><p>Forecast demand. Control operational risk. Test whether an AI agent is actually reliable. I turn complex workflows into evidence people can act on.</p><div className="hero-actions"><a href="#work">ENTER THE DECISION ROOM <span>-&gt;</span></a><a href="mailto:ridamelkaouiofficial@gmail.com">DISCUSS A PROBLEM <span>^</span></a></div><div className="hero-proof"><span>LIVE OPERATIONS</span><strong>Supplier quality at Magna International</strong><small>Industrial context / global collaboration / analytics built around action</small></div></div><div className="portrait-stage" aria-label="Portrait of Rida Melkaoui"><img src="./images/rida-decision-portrait.png" alt="Rida Melkaoui, industrial engineer and data/AI professional"/><span className="coordinate coordinate-a">33.9716 N</span><span className="coordinate coordinate-b">06.8498 W</span><div className="portrait-label"><span>RIDA MELKAOUI</span><small>OPERATIONS - DATA - DECISION</small></div></div><div className="hero-rail"><span>[ CURRENT SIGNAL ]</span><b>Kenitra, Morocco / Building at the intersection of industrial operations and intelligent systems</b></div></section> }

function SectionIntro({index,label,title,body}:{index:string;label:string;title:string;body?:string}){ return <header className="section-intro"><div><span>[{index}]</span><small>{label}</small></div><h2>{title}</h2>{body&&<p>{body}</p>}</header> }

function ProjectCase({project,active,onOpen}:{project:Project;active:boolean;onOpen:()=>void}){ return <article className={`project-case ${active?"active":""}`}><button className="case-cover" onClick={onOpen} aria-expanded={active}><div className="case-index">[{project.index}]</div><div className="case-title"><span>{project.title}</span><h3>{project.thesis}</h3><p>{project.question}</p></div><div className="case-result"><strong>{project.result}</strong><span>{project.resultNote}</span></div><span className="case-toggle">{active?"CLOSE -":"OPEN +"}</span></button>{active&&<div className="case-body"><div className="case-visual"><img src={project.image} alt={`${project.title} decision dashboard`}/><span>VERIFIED INTERFACE / DESKTOP</span></div><div className="case-evidence"><div><span className="mini-label">DECISION SUPPORTED</span><h4>{project.question}</h4></div><ol>{project.proof.map(item=><li key={item}>{item}</li>)}</ol><p>{project.stack}</p><small>{project.caveat}</small><div className="case-actions"><a href={project.lab} target="_blank" rel="noreferrer">OPEN LIVE LAB ^</a><a href={project.source} target="_blank" rel="noreferrer">READ THE BUILD ^</a></div></div></div>}</article> }

function Work(){ const[active,setActive]=useState<ProjectKey>("demand"); const activeProject=useMemo(()=>projects.find(project=>project.key===active)!,[active]); return <section className="work section-shell" id="work"><SectionIntro index="01" label="SELECTED SYSTEMS" title="Proof, not promises." body="Each build starts with an operating decision, uses public or non-confidential evidence, and ends with a tested interface a stakeholder can interrogate."/><div className="project-list">{projects.map(project=><ProjectCase key={project.key} project={project} active={project.key===active} onOpen={()=>setActive(project.key)}/>)}</div><div className="project-film"><img src={activeProject.detailImage} alt={`${activeProject.title} detailed interface view`}/><div><span>CASE {activeProject.index} / DETAIL VIEW</span><strong>{activeProject.title}</strong></div></div></section> }

function Method(){ const steps=[["01","FRAME","Name the decision, actor, action and cost of being wrong."],["02","PROVE","Build the data contract, quality gates, baselines and claim boundaries."],["03","MODEL","Use the simplest defensible statistical, optimization or AI method."],["04","OPERATE","Deliver an interface, exception queue and evidence trail - not a notebook alone."]]; return <section className="method" id="method"><SectionIntro index="02" label="HOW I WORK" title="From ambiguity to an operating decision."/><div className="method-track">{steps.map(([number,title,body])=><article key={number}><span>{number}</span><i></i><h3>{title}</h3><p>{body}</p></article>)}</div><div className="method-manifesto"><span>THE STANDARD</span><p>Useful analytics changes the next action. Reliable AI survives repetition. Good BI keeps the owner, exception and deadline visible.</p></div></section> }

function Experience(){ const[active,setActive]=useState(0); return <section className="experience section-shell" id="experience"><SectionIntro index="03" label="OPERATING CONTEXT" title="I learned analytics where decisions have consequences."/><div className="experience-grid"><div className="timeline-list">{timeline.map((item,index)=><button key={item.company} className={active===index?"active":""} onClick={()=>setActive(index)}><span>{item.period}</span><strong>{item.company}</strong><small>{item.role}</small></button>)}</div><article className="experience-detail"><div className="experience-code">0{active+1} / 04</div><span>{timeline[active].place}</span><h3>{timeline[active].statement}</h3><ul>{timeline[active].details.map(detail=><li key={detail}>{detail}</li>)}</ul>{active===0&&<div className="world-strip"><i>CN</i><i>ES</i><i>SK</i><i>DE</i><i>KR</i><i>MA</i><span>GLOBAL SUPPLIER RANGE</span></div>}</article></div></section> }

function Profile(){ const[copied,setCopied]=useState(false); const email="ridamelkaouiofficial@gmail.com"; const copy=async()=>{await navigator.clipboard.writeText(email);setCopied(true);window.setTimeout(()=>setCopied(false),1500)}; return <><section className="profile section-shell" id="profile"><SectionIntro index="04" label="PROFILE" title="Business context in. Decision system out."/><div className="profile-grid"><p className="profile-lead">Industrial & Production Engineer with hands-on supplier-quality responsibility and a portfolio spanning forecasting, optimization, BI and AI evaluation.</p><div className="capability-grid"><div><span>ANALYZE</span><p>SQL / Python / statistics / forecasting / experimentation / data quality</p></div><div><span>BUILD</span><p>Power BI / DAX / data models / React / APIs / automation / decision interfaces</p></div><div><span>OPERATE</span><p>Supplier quality / launches / 8D-CAPA / FMEA / Lean / cross-functional communication</p></div></div></div><div className="credential-rail"><div><span>EDUCATION</span><strong>Industrial & Production Engineering</strong><small>AIAC / 2022-2025</small><small>Preparatory Classes MPSI-MP / 2020-2022</small></div><div><span>CERTIFICATIONS</span><strong>IBM Data Analyst Professional Certificate</strong><small>EF SET C1 / TOEIC 855</small></div><div><span>LANGUAGES</span><strong>Arabic / French / English</strong><small>Native / Fluent / C1</small></div></div></section><footer id="contact" className="contact"><span className="contact-index">[05] CONTACT</span><h2>BRING ME THE<br/><em>MESSY PART.</em></h2><p>If the problem involves operational complexity, unreliable data, repeated manual decisions or AI that needs proof, I want to hear about it.</p><div className="contact-links"><a href={`mailto:${email}`}>EMAIL ME ^</a><button onClick={copy}>{copied?"EMAIL COPIED":"COPY EMAIL"}</button><a href="https://www.linkedin.com/in/rida-melkaoui-7bab50256/" target="_blank" rel="noreferrer">LINKEDIN ^</a><a href="https://github.com/RidaMelkaoui" target="_blank" rel="noreferrer">GITHUB ^</a></div><div className="footer-line"><span>RIDA MELKAOUI / 2026</span><span>INDUSTRIAL ENGINEER / DATA + AI / BI</span><span>KENITRA, MOROCCO</span></div></footer></> }

export default function App(){ useEffect(()=>{document.documentElement.classList.add("ready");return()=>document.documentElement.classList.remove("ready")},[]); return <><Header/><main id="main"><Hero/><Work/><Method/><Experience/><Profile/></main></> }
